version: "3.2"

services:
  chain:
    build:
      context: .
      dockerfile: ./docker/builder.fast-pioneer.Dockerfile
    container_name: ares-chain-0928
    image: aresprotocollab/ares_node_0928:latest
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
      - "9615:9615"
    volumes:
      - ./data/ares-manual-bridge:/data
    command: >
      ares-node --dev --tmp --chain pioneer --ws-external --rpc-external --rpc-cors=all --rpc-methods=Unsafe --name test-babe-node --warehouse http://api.aresprotocol.io -lares::price-estimates=debug -ltxpool=debug
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
